//@version=5
indicator(title="Chaikin Money Flow with MA", shorttitle="CMF+MA", format=format.price, precision=2)

// Check for volume data
var cumVol = 0.
cumVol += nz(volume)
if barstate.islast and cumVol == 0
    runtime.error("No volume is provided by the data vendor.")

// Input parameters
length = input.int(20, minval=1, title="CMF Length")
ma_length = input.int(5, minval=1, title="MA Length")
ma_length2 = input.int(20, minval=1, title="MA Length 2")
ma_length3 = input.int(50, minval=1, title="MA Length 3")

// Calculate CMF
ad = close==high and close==low or high==low ? 0 : ((2*close-low-high)/(high-low))*volume
mf = math.sum(ad, length) / math.sum(volume, length)

// Calculate Moving Average of CMF
mf_ma = ta.sma(mf, ma_length)
mf_ma2 = ta.sma(mf, ma_length2)
mf_ma3 = ta.sma(mf, ma_length3)

// Plot CMF
plot(mf, color=color.white, title="CMF")

// Plot Moving Average
plot(mf_ma, color=color.green, title="MA of CMF", linewidth = 2)
plot(mf_ma2, color=color.yellow, title="MA of CMF", linewidth = 2)
plot(mf_ma3, color=color.aqua, title="MA of CMF", linewidth = 2)

// Add zero line
hline(0, color=#787B86, title="Zero", linestyle=hline.style_dashed, linewidth = 2)
hline(0.30, color=#787B86, title="Overbough", linestyle=hline.style_dashed, linewidth = 1)
hline(-0.30, color=#787B86, title="Oversold", linestyle=hline.style_dashed, linewidth = 1)

// Add exit label when CMF crosses below 50-day MA
crossBelow = ta.crossunder(mf, mf_ma3)
if crossBelow
    label.new(bar_index, mf_ma3, text="!", style=label.style_label_down, color=color.yellow, textcolor=color.white, size = size.tiny)