//@version=5
indicator(title="Trend Strenth Oscillator", shorttitle="Entry", overlay=false)

// Inputs
basePeriods = input.int(26, minval=1, title="Base Line Length")
maPeriods = input.int(9, minval=1, title="Moving Average Length")
pointsPeriods = input.int(50, minval=1, title="Points Period")
avgLength = input.int(50, minval=1, title="Average Length")
lensig = input.int(14, title="ADX Smoothing", minval=1, maxval=50)
len = input.int(14, minval=1, title="DI Length")
trendLookback = input.int(5, minval=1, title="Trend Lookback Period")
cmfChangeThreshold = input.float(10, title="CMF Entry Threshold", step=0.01)

// Kijun Sen
donchian(len) => math.avg(ta.lowest(len), ta.highest(len))
baseLine = donchian(basePeriods)

// CMF
var cumVol = 0.
cumVol += nz(volume)
ad = close == high and close == low or high == low ? 0 : ((2 * close - low - high) / (high - low)) * volume
mf = math.sum(ad, avgLength) / math.sum(volume, avgLength)
avgCMF = ta.sma(mf, avgLength)

// Calculate CMF percentage increase
cmfPrev1 = nz(mf[1])
cmfPrev2 = nz(mf[2])
cmfPrev3 = nz(mf[3])
cmfPrev4 = nz(mf[4])
cmfPrev5 = nz(mf[5])
epsilon = 1e-10  // Small value to prevent division by zero

cmfChange1 = cmfPrev1 != 0 ? (mf - cmfPrev1) / math.abs(cmfPrev1) * 100 : (mf - cmfPrev1) / epsilon * 100
cmfChange2 = cmfPrev2 != 0 ? (mf - cmfPrev2) / math.abs(cmfPrev2) * 100 : (mf - cmfPrev2) / epsilon * 100
cmfChange3 = cmfPrev1 != 0 ? (mf - cmfPrev1) / math.abs(cmfPrev3) * 100 : (mf - cmfPrev3) / epsilon * 100
cmfChange4 = cmfPrev2 != 0 ? (mf - cmfPrev2) / math.abs(cmfPrev4) * 100 : (mf - cmfPrev4) / epsilon * 100
cmfChange5 = cmfPrev1 != 0 ? (mf - cmfPrev1) / math.abs(cmfPrev5) * 100 : (mf - cmfPrev5) / epsilon * 100

// DMI
up = ta.change(high)
down = -ta.change(low)
plusDM = na(up) ? na : (up > down and up > 0 ? up : 0)
minusDM = na(down) ? na : (down > up and down > 0 ? down : 0)
trur = ta.rma(ta.tr, len)
plus = fixnan(100 * ta.rma(plusDM, len) / trur)
minus = fixnan(100 * ta.rma(minusDM, len) / trur)

// Weekly Data
weeklyKijun = request.security(syminfo.tickerid, "W", baseLine)
weeklyCMF = request.security(syminfo.tickerid, "W", mf)
weeklyAvgCMF = request.security(syminfo.tickerid, "W", avgCMF)
weeklyPlus = request.security(syminfo.tickerid, "W", plus)
weeklyMinus = request.security(syminfo.tickerid, "W", minus)

// Trend Detection
isTrendingUp(series, lookback) =>
    series[0] > ta.sma(series, lookback)

isTrendingDown(series, lookback) =>
    series[0] < ta.sma(series, lookback)

// Function to calculate points
calculatePointsAbove(baseLine, weeklyKijun, mf, avgCMF, plus, minus, weeklyCMF, weeklyAvgCMF, weeklyPlus, weeklyMinus, crossWeeklyKijun) =>
    float localPoints = 0
    if isTrendingUp(baseLine, trendLookback)
        localPoints += 3
    if isTrendingDown(baseLine, trendLookback)
        localPoints -= 3
    if baseLine > ta.vwap(50)
        localPoints += 3
    if mf > 0
        localPoints += 3
    if mf < 0
        localPoints -= 15
    if mf > avgCMF
        localPoints += 3
    if mf < avgCMF
        localPoints -= 3
    if mf < 20
        localPoints += 3
    if mf > 20
        localPoints -= 3
    if cmfChange1 < -cmfChangeThreshold or cmfChange2 < -cmfChangeThreshold or cmfChange3 < -cmfChangeThreshold or cmfChange4 < -cmfChangeThreshold or cmfChange5 < -cmfChangeThreshold
        localPoints -= 5
    if cmfChange1 > cmfChangeThreshold or cmfChange2 > cmfChangeThreshold or cmfChange3 > cmfChangeThreshold or cmfChange4 > cmfChangeThreshold or cmfChange5 > cmfChangeThreshold
        localPoints += 5
    if plus > minus
        localPoints += 3
    if plus < minus
        localPoints -= 3
    if close > weeklyKijun
        localPoints += 2
    if crossWeeklyKijun
        localPoints += 3
    if isTrendingUp(weeklyKijun, trendLookback)
        localPoints += 3
    if close < weeklyKijun
        localPoints -= 10
    if weeklyPlus > weeklyMinus
        localPoints += 5
    if weeklyPlus < weeklyMinus
        localPoints -= 5
    if weeklyKijun > ta.vwap(50)
        localPoints += 3
    if weeklyCMF > 0
        localPoints += 3
    if weeklyCMF < 0
        localPoints -= 3
    if weeklyCMF > weeklyAvgCMF
        localPoints += 2
    localPoints

calculatePointsBelow(baseLine, weeklyKijun, mf, avgCMF, plus, minus, weeklyCMF, weeklyAvgCMF, weeklyPlus, weeklyMinus, crossWeeklyKijun) =>
    float localPoints = 0
    if isTrendingUp(baseLine, trendLookback)
        localPoints += 3
    if isTrendingDown(baseLine, trendLookback)
        localPoints -= 3
    if baseLine > ta.vwap(50)
        localPoints += 3
    if mf > 0
        localPoints += 3
    if mf < 0
        localPoints -= 10
    if mf > avgCMF
        localPoints += 3
    if mf < avgCMF
        localPoints -= 3
    if mf < 20
        localPoints += 3
    if mf > 20
        localPoints -= 3
    if cmfChange1 < -cmfChangeThreshold or cmfChange2 < -cmfChangeThreshold or cmfChange3 < -cmfChangeThreshold or cmfChange4 < -cmfChangeThreshold or cmfChange5 < -cmfChangeThreshold
        localPoints -= 5
    if cmfChange1 > cmfChangeThreshold or cmfChange2 > cmfChangeThreshold or cmfChange3 > cmfChangeThreshold or cmfChange4 > cmfChangeThreshold or cmfChange5 > cmfChangeThreshold
        localPoints += 5
    if plus > minus
        localPoints += 3
    if plus < minus
        localPoints -= 3
    if isTrendingUp(weeklyKijun, trendLookback)
        localPoints += 3
    if weeklyPlus > weeklyMinus
        localPoints += 5
    if weeklyPlus < weeklyMinus
        localPoints -= 5
    if weeklyKijun > ta.vwap(50)
        localPoints += 3
    if weeklyCMF > 0
        localPoints += 3
    if weeklyCMF < 0
        localPoints -= 3
    if weeklyCMF > weeklyAvgCMF
        localPoints += 2
    localPoints

// Calculate Points
points = 0.0

// Check if the crossover happened during the current period or in the last two periods
crossRecentKijun = ta.barssince(ta.crossover(close, baseLine)) <= 2
crossWeeklyKijun = ta.barssince(ta.crossover(close, weeklyKijun)) <= 2

// Use a single call to calculatePoints per logical block
if crossRecentKijun
    points += 5
    points += calculatePointsAbove(baseLine, weeklyKijun, mf, avgCMF, plus, minus, weeklyCMF, weeklyAvgCMF, weeklyPlus, weeklyMinus, crossWeeklyKijun)
else if close > baseLine
    points += 2
    if crossRecentKijun
        points += 3
    points += calculatePointsAbove(baseLine, weeklyKijun, mf, avgCMF, plus, minus, weeklyCMF, weeklyAvgCMF, weeklyPlus, weeklyMinus, crossWeeklyKijun)
else if crossWeeklyKijun
    points += 5
    points += calculatePointsAbove(baseLine, weeklyKijun, mf, avgCMF, plus, minus, weeklyCMF, weeklyAvgCMF, weeklyPlus, weeklyMinus, crossWeeklyKijun)
else if close > weeklyKijun
    points += 2
    if crossWeeklyKijun
        points += 3
    points += calculatePointsAbove(baseLine, weeklyKijun, mf, avgCMF, plus, minus, weeklyCMF, weeklyAvgCMF, weeklyPlus, weeklyMinus, crossWeeklyKijun)
else if close < baseLine
    points -= 5
    if close < weeklyKijun
        points -= 10
    points += calculatePointsBelow(baseLine, weeklyKijun, mf, avgCMF, plus, minus, weeklyCMF, weeklyAvgCMF, weeklyPlus, weeklyMinus, crossWeeklyKijun)
else if close < weeklyKijun
    points -=10
    points += calculatePointsBelow(baseLine, weeklyKijun, mf, avgCMF, plus, minus, weeklyCMF, weeklyAvgCMF, weeklyPlus, weeklyMinus, crossWeeklyKijun)

// Calculate moving average of Kijun
pointsMA = ta.sma(points,pointsPeriods)

// Plot the oscillator with conditional coloring
plot(points, "Points Oscillator", color=points >= 0 ? color.green : color.red, linewidth=2)
plot(pointsMA, "Points Oscillator", color=pointsMA >= 0 ? color.blue : color.yellow, linewidth=2)

// Add a zero line
hline(0, "Zero Line", color=color.gray, linestyle=hline.style_dotted)

// Add labels for crossovers and crossunders on the oscillator line
// if ta.crossover(close, baseLine)
//     label.new(bar_index, points, "D", color=color.green, textcolor=color.white, style=label.style_label_down, size=size.tiny)
// if ta.crossunder(close, baseLine)
//     label.new(bar_index, points, "D", color=color.red, textcolor=color.white, style=label.style_label_up, size=size.tiny)

// if ta.crossover(close, weeklyKijun)
//     label.new(bar_index, points, "W", color=color.green, textcolor=color.white, style=label.style_label_down, size=size.tiny)
// if ta.crossunder(close, weeklyKijun)
//     label.new(bar_index, points, "W", color=color.red, textcolor=color.white, style=label.style_label_up, size=size.tiny)

if ta.crossover(close, baseLine)
    label.new(bar_index, pointsMA, "D", color=color.green, textcolor=color.white, style=label.style_label_down, size=size.tiny)
if ta.crossunder(close, baseLine)
    label.new(bar_index, pointsMA, "D", color=color.red, textcolor=color.white, style=label.style_label_up, size=size.tiny)

if ta.crossover(close, weeklyKijun)
    label.new(bar_index, pointsMA, "W", color=color.green, textcolor=color.white, style=label.style_label_down, size=size.tiny)
if ta.crossunder(close, weeklyKijun)
    label.new(bar_index, pointsMA, "W", color=color.red, textcolor=color.white, style=label.style_label_up, size=size.tiny)